export const BOARDS = [
  {
    id: "m5stickcplus_11",
    name: "M5StickC Plus 1.1",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    bin: "/firmware/unigeek-m5stickcplus_11.bin",
    knownIssues: ["NRF24 module untested"],
  },
  {
    id: "m5stickcplus_2",
    name: "M5StickC Plus 2",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    bin: "/firmware/unigeek-m5stickcplus_2.bin",
    knownIssues: ["NRF24 module untested"],
  },
  {
    id: "t_lora_pager",
    name: "T-Lora Pager",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "NFC", "IR", "Sub-GHz", "LoRa", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-t_lora_pager.bin",
  },
  {
    id: "t_display",
    name: "T-Display",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "USB HID"],
    bin: "/firmware/unigeek-t_display.bin",
  },
  {
    id: "t_display_s3",
    name: "T-Display S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "USB HID"],
    bin: "/firmware/unigeek-t_display_s3.bin",
  },
  {
    id: "m5_cardputer",
    name: "M5 Cardputer",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-m5_cardputer.bin",
  },
  {
    id: "m5_cardputer_adv",
    name: "M5 Cardputer ADV",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-m5_cardputer_adv.bin",
  },
  {
    id: "diy_smoochie",
    name: "DIY Smoochie",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "NFC", "NRF24L01", "Sub-GHz", "USB HID"],
    bin: "/firmware/unigeek-diy_smoochie.bin",
  },
  {
    id: "t_embed_cc1101",
    name: "T-Embed CC1101",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Sub-GHz", "NRF24L01", "USB HID"],
    bin: "/firmware/unigeek-t_embed_cc1101.bin",
  },
  {
    id: "m5_cores3_unified",
    name: "M5 CoreS3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Touch", "USB HID"],
    bin: "/firmware/unigeek-m5_cores3_unified.bin",
    knownIssues: ["SD card doesn't work properly"],
  },
  {
    id: "m5sticks3",
    name: "M5StickC S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "USB HID"],
    bin: "/firmware/unigeek-m5sticks3.bin",
    knownIssues: ["CC1101, NRF24, and internal IR untested"],
  },
  {
    id: "cyd_2432w328r",
    name: "CYD 2432W328R",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    bin: "/firmware/unigeek-cyd_2432w328r.bin",
    knownIssues: ["New addition — most modules untested"],
  },
];