export const BOARDS = [
  {
    id: "m5stickcplus_11",
    name: "M5StickC Plus 1.1",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    bin: "/firmware/unigeek-m5stickcplus_11.bin",
    nav: [
      ["Default (Buttons)", [
        { input: "AXP power button", action: "Up" },
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — side button (short press)", action: "Down" },
        { input: "BTN_B — side button (hold >600ms)", action: "Back" },
      ], "No dedicated Back button — hold BTN_B to go back."],
      ["With M5Hat Mini EncoderC", [
        { input: "Encoder CCW (left turn)", action: "Up" },
        { input: "Encoder CW (right turn)", action: "Down" },
        { input: "Encoder push", action: "Select" },
        { input: "BTN_A (short press, release)", action: "Back" },
        { input: "AXP power button", action: "Left" },
        { input: "BTN_B (press, release)", action: "Right" },
      ], null],
    ],
  },
  {
    id: "m5stickcplus_2",
    name: "M5StickC Plus 2",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    bin: "/firmware/unigeek-m5stickcplus_2.bin",
    nav: [
      ["Default (Buttons)", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — bottom button (short press)", action: "Down" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], "No dedicated Back button — hold BTN_B to go back."],
      ["With M5Hat Mini EncoderC", [
        { input: "Encoder CCW (left turn)", action: "Up" },
        { input: "Encoder CW (right turn)", action: "Down" },
        { input: "Encoder push", action: "Select" },
        { input: "BTN_A (short press, release)", action: "Back" },
        { input: "BTN_UP (press, release)", action: "Left" },
        { input: "BTN_B (press, release)", action: "Right" },
      ], null],
    ],
  },
  {
    id: "m5sticks3",
    name: "M5StickC S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "USB HID"],
    bin: "/firmware/unigeek-m5sticks3.bin",
    knownIssues: ["CC1101, NRF24, and internal IR untested"],
    nav: [
      ["Buttons", [
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — single press", action: "Down" },
        { input: "BTN_B — double press (≤250ms)", action: "Up" },
        { input: "BTN_B — hold >600ms", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cardputer",
    name: "M5 Cardputer",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-m5_cardputer.bin",
    nav: [
      ["Keyboard", [
        { input: "Key ;", action: "Up" },
        { input: "Key .", action: "Down" },
        { input: "Key ,", action: "Left" },
        { input: "Key /", action: "Right" },
        { input: "Enter", action: "Select" },
        { input: "Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cardputer_adv",
    name: "M5 Cardputer ADV",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-m5_cardputer_adv.bin",
    nav: [
      ["Keyboard", [
        { input: "Key ;", action: "Up" },
        { input: "Key .", action: "Down" },
        { input: "Key ,", action: "Left" },
        { input: "Key /", action: "Right" },
        { input: "Enter", action: "Select" },
        { input: "Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cores3",
    name: "M5 CoreS3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Touch", "USB HID"],
    bin: "/firmware/unigeek-m5_cores3.bin",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "t_display",
    name: "T-Display",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "USB HID"],
    bin: "/firmware/unigeek-t_display.bin",
    nav: [
      ["Buttons", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_B — bottom button (single click)", action: "Down" },
        { input: "BTN_B — bottom button (double click, ≤250ms)", action: "Select" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_display_s3",
    name: "T-Display S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "USB HID"],
    bin: "/firmware/unigeek-t_display_s3.bin",
    nav: [
      ["Buttons", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_B — bottom button (single click)", action: "Down" },
        { input: "BTN_B — bottom button (double click, ≤250ms)", action: "Select" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_lora_pager",
    name: "T-Lora Pager",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "NFC", "IR", "Sub-GHz", "LoRa", "Keyboard", "USB HID"],
    bin: "/firmware/unigeek-t_lora_pager.bin",
    nav: [
      ["Encoder + Keyboard", [
        { input: "Encoder — turn CCW (left)", action: "Up" },
        { input: "Encoder — turn CW (right)", action: "Down" },
        { input: "Encoder — push", action: "Select" },
        { input: "Keyboard Enter", action: "Select" },
        { input: "Keyboard Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_embed_cc1101",
    name: "T-Embed CC1101",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Sub-GHz", "NRF24L01", "USB HID"],
    bin: "/firmware/unigeek-t_embed_cc1101.bin",
    nav: [
      ["Encoder", [
        { input: "Encoder — turn CW (right)", action: "Up" },
        { input: "Encoder — turn CCW (left)", action: "Down" },
        { input: "Encoder — push", action: "Select" },
        { input: "Back button", action: "Back" },
      ], null],
    ],
  },
  {
    id: "diy_smoochie",
    name: "DIY Smoochie",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "NFC", "NRF24L01", "Sub-GHz", "USB HID"],
    bin: "/firmware/unigeek-diy_smoochie.bin",
    nav: [
      ["Buttons", [
        { input: "BTN_UP", action: "Up" },
        { input: "BTN_DOWN", action: "Down" },
        { input: "BTN_LEFT — short press", action: "Left" },
        { input: "BTN_LEFT — hold >600ms", action: "Back" },
        { input: "BTN_RIGHT", action: "Right" },
        { input: "BTN_SEL — center button", action: "Select" },
      ], "No dedicated Back button — hold BTN_LEFT to go back."],
    ],
  },
  {
    id: "cyd_2432w328r",
    name: "CYD 2432W328R",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    bin: "/firmware/unigeek-cyd_2432w328r.bin",
    knownIssues: ["New addition — most modules untested"],
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
];
