#include "ChameleonMfuNdefScreen.h"
#include "utils/ble/ChameleonClient.h"
#include "utils/nfc/NdefBuilder.h"
#include "utils/nfc/NdefParser.h"
#include "utils/nfc/NfcDumpBuilder.h"
#include "core/Device.h"
#include "core/ScreenManager.h"
#include "ui/actions/InputTextAction.h"
#include "ui/actions/ShowStatusAction.h"
#include "ui/components/Header.h"
#include "ui/views/ProgressView.h"

namespace { void operationTitle(const char* t){Header h;h.render(t);} void prog(uint16_t d,uint16_t t){char m[36];snprintf(m,sizeof(m),"Writing pages (%u/%u)...",(unsigned)d,(unsigned)t);ProgressView::progress(m,t?(int)((uint32_t)d*100u/t):0);} }
const char* ChameleonMfuNdefScreen::title(){return _state==WRITE_MENU?"Write NDEF":_state==RESULT?"NDEF Details":_state==FILE_SELECT?"NDEF Files":"NDEF Operations";}
void ChameleonMfuNdefScreen::onInit(){goMenu();}
void ChameleonMfuNdefScreen::goMenu(){_state=MENU;setItems(_menu);render();}
void ChameleonMfuNdefScreen::goWrite(){_state=WRITE_MENU;setItems(_write);render();}
void ChameleonMfuNdefScreen::add(const String&a,const String&b){if(_n>=24)return;_l[_n]=a;_v[_n]=b;_rows[_n]={_l[_n].c_str(),_v[_n].c_str()};++_n;}
bool ChameleonMfuNdefScreen::readImage(uint8_t*&img,size_t&len,uint8_t uid[7]){auto&c=ChameleonClient::get();c.setMode(1);ChameleonClient::MfuTagInfo info={};if(!c.mfuDetect(&info)){c.setMode(0);ShowStatusAction::show("No Type 2 tag");return false;}len=(size_t)info.pages*4u;img=(uint8_t*)malloc(len);if(!img){c.setMode(0);ShowStatusAction::show("Out of memory");return false;}memcpy(uid,info.uid,7);uint16_t got=0;ProgressView::init();char m[36];snprintf(m,sizeof(m),"Reading pages (0/%u)...",(unsigned)info.pages);ProgressView::progress(m,0);bool ok=c.mfuReadDump(info,img,(uint16_t)len,&got,[](uint16_t d,uint16_t t){char x[36];snprintf(x,sizeof(x),"Reading pages (%u/%u)...",(unsigned)d,(unsigned)t);ProgressView::progress(x,t?(int)((uint32_t)d*100u/t):0);});ProgressView::finish();c.setMode(0);if(!ok){free(img);img=nullptr;ShowStatusAction::show("Read failed");return false;}len=got;return true;}
void ChameleonMfuNdefScreen::show(const uint8_t*ndef,size_t len,const uint8_t uid[7]){_state=RESULT;_n=0;String u;for(int i=0;i<7;i++){char b[4];snprintf(b,sizeof(b),"%02X%s",uid[i],i<6?":":"");u+=b;}add("UID",u);NdefParser::Result r;if(!ndef||!len||!NdefParser::parse(ndef,len,r)){add("NDEF","Not found");}else{switch(r.kind){case NdefParser::RECORD_TEXT:add("NDEF","Text");add("Text",r.text);break;case NdefParser::RECORD_URL:add("NDEF","URI");add("URI",r.uri);break;case NdefParser::RECORD_PHONE:add("NDEF","Phone");add("Phone",r.phone);break;case NdefParser::RECORD_EMAIL:add("NDEF","Email");add("Mail",r.email);break;case NdefParser::RECORD_VCARD:add("NDEF","vCard");add("Contact",r.contact);break;default:add("NDEF","Unsupported");break;}}_view.resetScroll();_view.setRows(_rows,_n);render();}
void ChameleonMfuNdefScreen::read(){operationTitle("Read NDEF");_running=true;uint8_t*img=nullptr,uid[7]={};size_t len=0;if(readImage(img,len,uid)){const uint8_t*n=nullptr;size_t nl=0;if(NdefParser::extractType2Ndef(img,len,&n,&nl))show(n,nl,uid);else show(nullptr,0,uid);free(img);}_running=false;}
bool ChameleonMfuNdefScreen::writeRecord(const uint8_t*ndef,size_t nl,const char* opTitle){operationTitle(opTitle);auto&c=ChameleonClient::get();c.setMode(1);ChameleonClient::MfuTagInfo info={};if(!c.mfuDetect(&info)||info.type!=ChameleonClient::MFU_NTAG215){c.setMode(0);ShowStatusAction::show("Write supports NTAG215");return false;}uint8_t img[NfcDumpBuilder::NTAG215_SIZE];size_t len=0;if(!NfcDumpBuilder::buildNtag215(info.uid,ndef,nl,img,len,sizeof(img))){c.setMode(0);ShowStatusAction::show("NDEF does not fit");return false;}ProgressView::init();bool ok=c.mfuWriteNtag215User(img,(uint16_t)len,prog,&info);ProgressView::finish();c.setMode(0);ShowStatusAction::show(ok?"NDEF written":"NDEF write failed");return ok;}
bool ChameleonMfuNdefScreen::format(const char* opTitle){return writeRecord(nullptr,0,opTitle);}
void ChameleonMfuNdefScreen::erase(){bool ok=format("Erase NDEF"); if(ok) ShowStatusAction::show("NDEF erased"); goMenu();}
void ChameleonMfuNdefScreen::writeBuilt(uint8_t k){String a=InputTextAction::popup(k==0?"Text":k==1?"URL":k==2?"Phone":"Email","");if(InputTextAction::wasCancelled()||!a.length()){goWrite();return;}uint8_t n[500];size_t l=0;bool ok=k==0?NdefBuilder::buildText(a,n,l,sizeof(n)):k==1?NdefBuilder::buildUrl(a,n,l,sizeof(n)):k==2?NdefBuilder::buildPhone(a,n,l,sizeof(n)):NdefBuilder::buildEmail(a,n,l,sizeof(n));if(ok)writeRecord(n,l,"Write NDEF");else ShowStatusAction::show("Cannot build NDEF");goWrite();}
void ChameleonMfuNdefScreen::files(){_state=FILE_SELECT;if(!_pickDir.length())_pickDir="/unigeek/nfc/ndefs";_browser.root="/unigeek/nfc/ndefs";uint8_t n=_browser.load(this,_pickDir,".ndef");setItems(_browser.items(),n);render();if(!n)ShowStatusAction::show("No .ndef files");}
void ChameleonMfuNdefScreen::fileSelected(uint8_t i){if(i>=_browser.count())return;auto&e=_browser.entry(i);if(e.isDir){_pickDir=e.path;files();return;}String raw=Uni.Storage->readFile(e.path.c_str());if(!raw.length()){ShowStatusAction::show("Empty file");return;}writeRecord((const uint8_t*)raw.c_str(),raw.length(),"Write NDEF");files();}
void ChameleonMfuNdefScreen::onItemSelected(uint8_t i){if(_state==MENU){if(i==0)read();else if(i==1)goWrite();else if(i==2)erase();else if(i==3){format("Format NDEF");goMenu();}}else if(_state==WRITE_MENU){if(i<4)writeBuilt(i);else if(i==4){String name=InputTextAction::popup("Name","");if(InputTextAction::wasCancelled()){goWrite();return;}String phone=InputTextAction::popup("Phone","");if(InputTextAction::wasCancelled()){goWrite();return;}String email=InputTextAction::popup("Email","");if(InputTextAction::wasCancelled()){goWrite();return;}uint8_t n[500];size_t l=0;if(NdefBuilder::buildVcard(name,"","",phone,email,"",n,l,sizeof(n)))writeRecord(n,l,"Write NDEF");else ShowStatusAction::show("Cannot build vCard");goWrite();}else files();}else if(_state==FILE_SELECT)fileSelected(i);}
void ChameleonMfuNdefScreen::onUpdate(){if(_state==RESULT){if(Uni.Nav->wasPressed()){auto d=Uni.Nav->readDirection();if(d==INavigation::DIR_BACK)goMenu();else _view.onNav(d);}return;}ListScreen::onUpdate();}
void ChameleonMfuNdefScreen::onRender(){if(_state==RESULT){_view.render(bodyX(),bodyY(),bodyW(),bodyH());return;}ListScreen::onRender();}
void ChameleonMfuNdefScreen::onBack(){if(_state==WRITE_MENU||_state==RESULT){goMenu();return;}if(_state==FILE_SELECT){_pickDir="";goWrite();return;}Screen.goBack();}
